### ISSUE TITLE
Error: Cannot find module 'synaptic' after installing.

### ISSUE THREAD

**Issue by JPaulMora** [cazala/synaptic#109]
````
$ npm install synaptic --save
$ npm list synaptic
iamdinosaur@1.0.0 /Users/JP/git/IAMDinosaur
└── synaptic@1.0.5 

$ node index
module.js:440
    throw err;
    ^

Error: Cannot find module 'synaptic'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/JP/git/IAMDinosaur/Learner.js:1:78)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
````

Trying to run this: git://github.com/ivanseidel/IAMDinosaur.git
Thanks

**Comment by cazala** [comment]
This should be fixed in  [v1.0.6](https://github.com/cazala/synaptic/releases)
