### ISSUE TITLE
Blob is undefined

### ISSUE THREAD

**Issue by ernestp** [cazala/synaptic#297]
I run Trainer from node.js project but receive error:

Promise error:  ReferenceError: Blob is not defined
    at Perceptron.worker (/my_project/node_modules/synaptic/dist/synaptic.js:946:18)
    at Trainer.workerTrain (/my_project/node_modules/synaptic/dist/synaptic.js:1974:33)
    at /my_project/node_modules/synaptic/dist/synaptic.js:1908:11
    at new Promise (<anonymous>)
    at Trainer.trainAsync (/my_project/node_modules/synaptic/dist/synaptic.js:1906:14)

**Comment by ernestp** [comment]
Found comment that it work only in Browser, closing issue.
